# Generated by Django 4.2.13 on 2024-08-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
